functions:
  - isLoggedIn(): auth.uid !== null
  - isUser(username): auth.uid === username
  - isAdmin(): root.users[auth.uid].admin === true

schema: {}

access:
  - location: /
    .read: isAdmin()
    .write: isAdmin()

  #- location: /users/$userid/
    #read: isUser($userid)

  #- location: /users/$userid/email/
    #write: isUser($userid)
  #- location: /users/$userid/firstName/
    #write: isUser($userid)
  #- location: /users/$userid/lastName/
    #write: isUser($userid
